cargo-features = ["edition2024"]

[package]
name = "transfersol"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "2.3.0"
borsh="1.0.0"
solana-system-interface = "1.0.0"
