cargo-features = ["edition2024"]

[package]
name = "testsolanaprogram"
version = "0.1.0"
edition = "2024"

[dependencies]
solana-program = "2.3.0"
borsh = "0.10.3"
borsh-derive = "0.10.3"

[lib]
crate-type = ["cdylib", "lib"]
